# Generated by Django 3.2.6 on 2021-08-13 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('discount_rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discount',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.TextField(primary_key=True, serialize=False)),
                ('station_name', models.TextField()),
            ],
            options={
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.TextField(primary_key=True, serialize=False)),
                ('mon', models.BooleanField()),
                ('tue', models.BooleanField()),
                ('wed', models.BooleanField()),
                ('thu', models.BooleanField()),
                ('fri', models.BooleanField()),
                ('sat', models.BooleanField()),
                ('sun', models.BooleanField()),
                ('ending_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending', to='Filter.station')),
                ('starting_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting', to='Filter.station')),
            ],
            options={
                'db_table': 'train',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('stop_sequence', models.IntegerField()),
                ('arrival_time', models.TextField(blank=True, null=True)),
                ('departure_time', models.TextField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filter.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filter.train')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('fare_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_fare', models.FloatField()),
                ('standard_fare', models.FloatField()),
                ('non_reserved_fare', models.FloatField()),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='Filter.station')),
                ('origin_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='Filter.station')),
            ],
            options={
                'db_table': 'fare',
            },
        ),
    ]
